sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: java
 
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
 
 
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  
  
script: mvn test