#set language
language: java


addons:
 chrome: stable
 
before_install:
 - wget http://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip -P ~/
 - unzip ~/chromedriver_linux64.zip -d ~/
 - rm ~/chromedriver_linux64.zip
 - sudo mv -f ~/chromedriver /usr/local/share/
 - sudo chmod +x /usr/local/share/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
 - sleep 3
 

script:
 - mvn test
 
after_success:
 - coverage xml
 - rtn=$(curl https://deepsource.io/cli | sh) 
 - echo $rtn
 - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml