
dist:xenial
language: java
 
addons: 
chrome : stable

 before_script: 
 -wget http://chromedriver.storage.googleapis.com/2.6/chromedriver_linux64.zip
 -unzip chromedriver_linux64.zip -d/home/travis/virtualenv/python2.7.12/bin/
 -export CHROME_BIN=/usr/bin/chromium-browser
 
script: mvn test